- name: Collect VM metrics
  hosts: env_dev
  become: true
  gather_facts: true
  tasks:
    # For our ubuntu machines as well
    - name: Install systat (for mpstat)
      apt:
        name: mpstat
        state: present
      when: ansible_os_family == "Debian"
    
    - name: Install systat (for mpstat)
      apt:
        name: mpstat
        state: present
      when: ansible_os_family == "RedHat"
    
    - name: Get CPU utilization for VM
      shell: "mpstat 1 1 | awk '/Average/ && $NF ~ /[0-9.]+/ {print 100 - $NF}'"
      register: cpu_usage
    
    - name: Get Memory utilization
      shell: "free | awk '/Mem/ {printf(\"%.2f\", $3/$2 * 100.00) }'"
      register: memory_usage

    - name: Get disk utilization
      shell: "df / | awk 'NR==2 {print $5}' | tr -d '%''"
      register: disk_usage

    - name: set metrics facts
      set_fact:
        vm_metrics:
          cpu: "{{cpu_usage.stdout | float | round(2)}}"
          memory: "{{memory_usage | float | round(2)}}"
          disk: "{{disk_usage | float | round(2)}}"
